version: '3.8'

networks:
  fullstack_network:
    name: ${PREFIX}network

services:
  api:
    image: davidthorn/symfony:5.3.5
    user: www-data
    container_name: ${PREFIX}php
    volumes:
      - ${APP_SOURCE}:${APP_WORKING_DIR}
      - ./build/conf/project.ini:/usr/local/etc/php/conf.d/project.ini
    networks:
        - fullstack_network

  nginx:
      image: nginx:latest
      container_name: ${PREFIX}nginx
      volumes:
        - ${APP_SOURCE}:${APP_WORKING_DIR}
        - ./build/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
        - "3000:80"
      networks:
        - fullstack_network
      depends_on:
        - react

  react:
    image: davidthorn/react-app:dev
    container_name: ${PREFIX}web
    volumes:
#      - node_modules:/var/www/html/node_modules
      - ./react:/var/www/html
    networks:
      - fullstack_network

volumes:
  node_modules: