version: '3.8'

networks:
  symfony_network:
    name: ${PREFIX}network

services:
  php:
    image: davidthorn/symfony:5.3.5
    user: www-data
    container_name: ${PREFIX}php
    volumes:
      - ${APP_SOURCE}:${APP_WORKING_DIR}
      - ./build/conf/project.ini:/usr/local/etc/php/conf.d/project.ini
    networks:
        - symfony_network
    depends_on: 
      - mysql
  
  nginx:
      image: nginx:latest
      container_name: ${PREFIX}nginx
      environment:
        - NGINX_HOST=david.springlane
      volumes:
        - ${APP_SOURCE}:${APP_WORKING_DIR}
        - ./build/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - ${NGINX_PORT}:80
      networks:
        - symfony_network
      depends_on: 
        - php

  mysql:
      image: mysql:${MYSQL_VERSION}
      container_name: ${PREFIX}mysql
      env_file:
        - ./build/conf/mysql.env
      volumes:
        - symfony_db_data:/var/lib/mysql
      ports:
        - ${MYSQL_SERVICE_PORT}:3306
      networks:
        - symfony_network

  admin:
    image: phpmyadmin:latest
    ports:
      - ${PHPADMIN_SERVICE_PORT}:80
    container_name: ${PREFIX}admin
    env_file:
      - ./build/conf/admin.env
    networks:
      - symfony_network
    
volumes:
  symfony_db_data:
    name: "${PREFIX}mysql_data"
    
