api:
  resource: '../src/Controller/Api/'
  type: annotation
  prefix: '/api'
  name_prefix: 'app_api_'

frontend:
  resource: '../src/Controller/Frontend/Pages'
  type: annotation
  name_prefix: 'app_pages_'

account:
  resource: '../src/Controller/Frontend/Account'
  prefix: '/account'
  type: annotation
  name_prefix: 'app_account_'

auth:
  resource: '../src/Controller/Frontend/Auth'
  type: annotation
  name_prefix: 'app_auth_'

admin:
  resource: '../src/Controller/Admin/Core'
  prefix: '/admin'
  type: annotation
  name_prefix: 'app_admin_'

shopware:
  resource: '../src/Controller/Admin/Shopware'
  prefix: '/admin/shopware'
  type: annotation
  name_prefix: 'app_shopware_'