#shopping_list_get:
#    path: /api/shopping/list
#    methods: GET
#    controller: App\Controller\ShoppingListRestController::index
#
#shopping_list_post:
#    path: /api/shopping/list
#    methods: POST
#    controller: App\Controller\ShoppingListRestController::create
#
#shopping_list_put:
#    path: /api/shopping/list/{id}
#    methods: [PUT]
#    controller: App\Controller\ShoppingListRestController::update
#
#shopping_list_delete:
#    path: /api/shopping/list/{id}
#    methods: [DELETE]
#    controller: App\Controller\ShoppingListRestController::delete
