api_item:
    path: /api/default/{id}
    methods: GET
    controller: App\Controller\DefaultController::item

api_list:
    path: /api/default
    methods: GET
    controller: App\Controller\DefaultController::index

api_post:
    path: /api/default
    methods: POST
    controller: App\Controller\DefaultController::create

api_put:
    path: /api/default/{id}
    methods: [PUT]
    controller: App\Controller\DefaultController::update

api_delete:
    path: /api/default/{id}
    methods: [DELETE]
    controller: App\Controller\DefaultController::delete
