basic_info_get:
  path: /api/basic/info/{id?}
  methods: ["GET", "DELETE", "POST", "PUT"]
  host: api.localhost
  requirements:
    id: '\d*?'
  controller: App\Controller\BasicInfoController::entryPoint