basic_info_get:
    path: /api/basic/info/{id}
    methods: GET
    controller: App\Controller\BasicInfoController::item

basic_info_list:
    path: /api/basic/info
    methods: GET
    controller: App\Controller\BasicInfoController::index

basic_info_post:
    path: /api/basic/info
    methods: POST
    controller: App\Controller\BasicInfoController::create

basic_info_put:
    path: /api/basic/info/{id}
    methods: [PUT]
    controller: App\Controller\BasicInfoController::update
basic_info_delete:
    path: /api/basic/info/{id}
    methods: [DELETE]
    controller: App\Controller\BasicInfoController::delete
