monolog:
    channels: ["rest"]
    handlers:
        cache:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.cache.log"
            level: debug
            channels: [ "cache" ]
        security:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.security.log"
            level: debug
            channels: [ "security" ]
        router:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.router.log"
            level: debug
            channels: [ "router" ]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            level: debug
            channels: [ "doctrine" ]
        request:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.request.log"
            level: debug
            channels: ["request"]
        rest:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.rest.log"
            level: debug
            channels: [ "rest" ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
