doctrine:
    dbal:
        dbname: '%env(DATABASE_NAME)%'
        host: mysql # Refers to the mysql docker container service name not the container_name.
        port: 3306
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: pdo_mysql
        server_version: '5.7'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
