doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: david
                host: mysql
                port: 3306
                user: david
                password: 123456
                driver: pdo_mysql
                server_version: '5.7'
                charset: UTF8
            shopware:
                dbname: shopware
                host: shopware
                port: 3306
                user: shopware
                password: 123456
                driver: pdo_mysql
                server_version: '5.7'
                charset: UTF8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App\Entity
            shopware:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: shopware
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Shopware'
                        prefix: 'App\Entity\Shopware'
                        alias: App\Entity\Shopware
